version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm start
  nginx:
    image: nginx:latest
    ports:
      - 9443:443
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    depends_on:
      - app
